### ISSUE TITLE
Figure out how we'll use JSON / JSONP to get the bill data on the site

### ISSUE THREAD

**Issue by freejoe76** [denverpost/bill-tracker#3]
ONE BIG THING TO CONSIDER: Publishing with javascript reduces the SEO value of this data. But is there SEO value for this data? Some of it (people's names and bill names), probably, yes.

THERE ARE AT LEAST TWO FACETS TO THIS ISSUE:
1. What's the homepage?
2. How do we integrate specific bills into articles?
3. Are there any intermediary main-site publishing bits ("This Week In The State House / Senate")?

**Comment by danielpetty** [comment]
If possible to avoid, would be preferred (I'm preaching to the choir here)

**Comment by freejoe76** [comment]
Petty, would you prefer we published this data on www.denverpost.com with screenscrapes or with iframes?

**Comment by freejoe76** [comment]
Related: https://github.com/denverpost/bill-tracker/issues/10 and https://github.com/denverpost/bill-tracker/issues/44 and https://github.com/denverpost/bill-tracker/issues/45

**Comment by freejoe76** [comment]
Iframe'ing in the Bill Tracker homepage is actually pretty good <-- words I never thought I'd write.
